const list = [
  {
    id: 1,
    title: "Smart LED TV",
    brand: "Samsung",
    price: 79999,
    img: "https://zebronics.com/cdn/shop/files/ZEB-55W2-pic1.jpg?v=1694521223&width=2048",
    amount: 1,
  },
  {
    id: 2,
    title: "Bluetooth Soundbar",
    brand: "Sony",
    price: 2499,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNV0me-Udtb25qMWFWqDJb5R1raNtT1hlSVQ&usqp=CAU",
    amount: 1,
  },
  {
    id: 3,
    title: "Wireless Charging Pad",
    brand: "Anker",
    price: 2999,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ_vAvX7fm-D67zV_fUCIFRDrDqBicFB9usQ&usqp=CAU",
    amount: 1,
  },
  {
    id: 4,
    title: "Portable Bluetooth Speaker",
    brand: "JBL",
    price: 999,
    img: "https://image.made-in-china.com/318f0j00WEDUoLyqClbN/New-Jb-L-Pluse-5-Bluetooth-Speaker-Full-Screen-Colorful-Wireless-Bluetooth-Speaker-RGB-Colorful-Lumi-mp4.webp",
    amount: 1,
  },
  {
    id: 5,
    title: "Smart Home Security Camera",
    brand: "Ring",
    price: 19999,
    img: "https://m.media-amazon.com/images/I/51j97Tyr2uL._AC_UF1000,1000_QL80_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Wireless Gaming Mouse",
    brand: "Logitech",
    price: 499,
    img: "https://i.pinimg.com/originals/94/aa/39/94aa39f9da16f6122010b1fdbb036aa9.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Robot Vacuum Cleaner",
    brand: "iRobot",
    price: 6999,
    img: "https://c8.alamy.com/comp/R24J62/3d-rendering-cute-robotic-vacuum-cleaner-isolated-on-white-R24J62.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Electric Toothbrush",
    brand: "Philips Sonicare",
    price: 5999,
    img: "https://www.shutterstock.com/image-vector/realistic-detailed-3d-electric-toothbrush-260nw-2248562029.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Fitness Tracker",
    brand: "Fitbit",
    price: 12999,
    img: "https://images.meesho.com/images/products/336278644/r02co_512.webp",
    amount: 1,
  },
  {
    id: 10,
    title: "Wireless Earbuds",
    brand: "Bose",
    price: 1999,
    img: "https://cdn.mos.cms.futurecdn.net/GHnJBkCHn22NgNGQWtpxhF-1200-80.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Digital Camera",
    brand: "Canon",
    price: 49999,
    img: "https://m.media-amazon.com/images/I/61oCyMDOI+L._AC_UF1000,1000_QL80_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Wireless Keyboard and Mouse Combo",
    brand: "HP",
    price: 399,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNyaxdYsLaqlXFngXWR7njIfGONrvMAcJCrw&usqp=CAU",
    amount: 1,
  },
];

export default list;
